[project]
name = "mutatio"
version = "0.1.0"
description = "A simple terminal user interface to mass rename files using regular expressions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=6.1.0",
]
